# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e11e90cda416b55f5cf011ecc7bdb7810dd87ca2ed83663facf44d8dbf4f578cf4fcf619a2b07dd0da7b3281568858f20ef90d14e08b39c16f0e443114cf96

test:
  secret_key_base: 6d40d317f78c9ad3dbfa16d3067737951a9e8f72a6158502ced497c2c8596205482b1ca1cdf9b834437b2e95f2726eac475c44244806482121ac58ad727533f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
